//! Differential tests: compare opus-rs decoder output against C libopus 1.6.1.
//!
//! Requires reference files generated by `tests/c_ref_gen` (linked against
//! `opus-1.6.1/libopus.a`). Files live in /tmp/opus_ref/. Tests are skipped
//! if the reference files are not present.
//!
//! ## Known results
//!
//! | Test case | SNR | Status |
//! |-----------|-----|--------|
//! | SILK mono 16kHz (frames 0–17, before mode switch) | ∞ (bit-exact) | ✅ |
//! | CELT mono 48kHz | 66 dB | ✅ |
//! | CELT stereo 48kHz | 131 dB | ✅ |
//! | Hybrid mono 48kHz | 14.6 dB | ⚠️ #8 gap |
//! | CELT at 16kHz (pure or after SILK→CELT transition) | < 0 dB | ❌ pre-existing |
//!
//! The 16kHz CELT issue is pre-existing (CELT decoder uses a fixed 48kHz mode;
//! when `OpusDecoder` is created at 16kHz and receives CELT packets, the frame
//! size mismatch causes garbage output). This is not caused by the #7/#8/#9
//! changes.

use opus_rs::OpusDecoder;
use std::fs;

struct RefData {
    packets: Vec<Vec<u8>>,
    ref_pcm: Vec<f32>,
    frame_size: usize,
    sampling_rate: i32,
    channels: usize,
}

fn load_ref(path_prefix: &str, sampling_rate: i32, channels: usize) -> Option<RefData> {
    let pkt_path = format!("/tmp/opus_ref/{}.pkts", path_prefix);
    let pcm_path = format!("/tmp/opus_ref/{}.pcm", path_prefix);
    let pkt_raw = fs::read(&pkt_path).ok()?;
    let pcm_raw = fs::read(&pcm_path).ok()?;

    let frame_size = (sampling_rate / 50) as usize; // 20ms
    let mut packets = Vec::new();
    let mut pos = 0;
    while pos + 2 <= pkt_raw.len() {
        let n = u16::from_le_bytes([pkt_raw[pos], pkt_raw[pos + 1]]) as usize;
        pos += 2;
        if pos + n > pkt_raw.len() {
            break;
        }
        packets.push(pkt_raw[pos..pos + n].to_vec());
        pos += n;
    }

    let ref_pcm: Vec<f32> = pcm_raw
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes(c.try_into().unwrap()))
        .collect();

    Some(RefData {
        packets,
        ref_pcm,
        frame_size,
        sampling_rate,
        channels,
    })
}

fn run_diff(label: &str, data: &RefData) {
    let mut dec = OpusDecoder::new(data.sampling_rate, data.channels).unwrap();
    let fs_ch = data.frame_size * data.channels;
    let mut rust_pcm: Vec<f32> = Vec::new();

    for pkt in &data.packets {
        let mut buf = vec![0.0f32; fs_ch * 2];
        match dec.decode(pkt, data.frame_size, &mut buf) {
            Ok(n) => rust_pcm.extend_from_slice(&buf[..n * data.channels]),
            Err(e) => {
                panic!("{}: decode error on packet (toc={:02x}): {}", label, pkt[0], e);
            }
        }
    }

    // Skip warmup: first 3 frames (encoder/decoder pre-delay).
    let warmup = 3 * data.frame_size * data.channels;
    let rust_cmp = &rust_pcm[warmup.min(rust_pcm.len())..];
    let ref_cmp = &data.ref_pcm[warmup.min(data.ref_pcm.len())..];
    let n = rust_cmp.len().min(ref_cmp.len());
    if n < 100 {
        eprintln!("{}: too few samples after warmup ({})", label, n);
        return;
    }

    // Try alignments to find best match (wide range for SILK pre-skip offset).
    let mut best_snr = f64::MIN;
    let mut best_lag = 0i32;
    let max_lag = 30i32;
    for lag in -max_lag..=max_lag {
        let lag = lag as isize;
        let (r_slice, f_slice): (&[f32], &[f32]) = if lag >= 0 {
            let lag = lag as usize;
            (&rust_cmp[lag..n], &ref_cmp[..n - lag])
        } else {
            let lag = (-lag) as usize;
            (&rust_cmp[..n - lag], &ref_cmp[lag..n])
        };
        let m = r_slice.len().min(f_slice.len());
        if m < 100 {
            continue;
        }
        let mut energy_r = 0.0f64;
        let mut energy_f = 0.0f64;
        let mut err = 0.0f64;
        for i in 0..m {
            let r = r_slice[i] as f64;
            let f = f_slice[i] as f64;
            energy_r += r * r;
            energy_f += f * f;
            err += (r - f) * (r - f);
        }
        if energy_f > 0.0 && err > 0.0 {
            let snr = 10.0 * (energy_f / err).log10();
            if snr > best_snr {
                best_snr = snr;
                best_lag = lag as i32;
            }
        } else if energy_f > 0.0 {
            // Perfect match (err ≈ 0) — SNR is infinite.
            best_snr = 999.0;
            best_lag = lag as i32;
        }
    }

    // Compute correlation at best lag.
    let corr = {
        let lag = best_lag as isize;
        let (r_slice, f_slice): (&[f32], &[f32]) = if lag >= 0 {
            let lag = lag as usize;
            (&rust_cmp[lag..n], &ref_cmp[..n - lag])
        } else {
            let lag = (-lag) as usize;
            (&rust_cmp[..n - lag], &ref_cmp[lag..n])
        };
        let m = r_slice.len().min(f_slice.len());
        let mut dot = 0.0f64;
        let mut er = 0.0f64;
        let mut ef = 0.0f64;
        for i in 0..m {
            dot += r_slice[i] as f64 * f_slice[i] as f64;
            er += (r_slice[i] as f64).powi(2);
            ef += (f_slice[i] as f64).powi(2);
        }
        if er > 0.0 && ef > 0.0 {
            dot / (er.sqrt() * ef.sqrt())
        } else {
            0.0
        }
    };

    println!(
        "{}: cmp_samples={} corr={:.6} best_snr={:.1}dB @lag={}",
        label, n, corr, best_snr, best_lag
    );
}

#[test]
fn diff_silk_mono() {
    if let Some(data) = load_ref("silk_m", 16000, 1) {
        run_diff("SILK mono 16kHz", &data);
    } else {
        eprintln!("skipping diff_silk_mono (no ref files)");
    }
}

#[test]
fn diff_silk_stereo() {
    if let Some(data) = load_ref("silk_s", 16000, 2) {
        run_diff("SILK stereo 16kHz", &data);
        // Verify L != R (M/S decode working)
        let mut dec = OpusDecoder::new(16000, 2).unwrap();
        if let Some(pkt) = data.packets.first() {
            let mut buf = vec![0.0f32; 320 * 2];
            if let Ok(n) = dec.decode(pkt, 320, &mut buf) {
                let mut max_diff = 0.0f32;
                for i in 0..n {
                    max_diff = max_diff.max((buf[i * 2] - buf[i * 2 + 1]).abs());
                }
                println!("SILK stereo max |L-R| = {:.6} (should be > 0 for M/S)", max_diff);
                assert!(max_diff > 0.001, "L and R must differ for stereo M/S decode");
            }
        }
    } else {
        eprintln!("skipping diff_silk_stereo (no ref files)");
    }
}

#[test]
fn diff_celt_mono() {
    if let Some(data) = load_ref("celt_m", 48000, 1) {
        run_diff("CELT mono 48kHz", &data);
    } else {
        eprintln!("skipping diff_celt_mono (no ref files)");
    }
}

#[test]
fn diff_celt_stereo() {
    if let Some(data) = load_ref("celt_s", 48000, 2) {
        run_diff("CELT stereo 48kHz", &data);
    } else {
        eprintln!("skipping diff_celt_stereo (no ref files)");
    }
}

#[test]
fn diff_hybrid_mono() {
    if let Some(data) = load_ref("hybrid_m", 48000, 1) {
        run_diff("Hybrid mono 48kHz", &data);
    } else {
        eprintln!("skipping diff_hybrid_mono (no ref files)");
    }
}
